# Generated by Django 4.2.7 on 2023-11-04 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='uploaded_at',
        ),
        migrations.AddField(
            model_name='userdetails',
            name='disease',
            field=models.CharField(default='No Disease', max_length=100),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='doctor_name',
            field=models.CharField(default='No Name', max_length=100),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='fees',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='hospital_address',
            field=models.TextField(default='No Address'),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='hospital_name',
            field=models.CharField(default='no Hospital Name', max_length=100),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='image_type',
            field=models.CharField(choices=[('Xray', 'X-ray'), ('Prescription', 'Prescription'), ('Other', 'Other')], default='Other', max_length=20),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='image',
            field=models.ImageField(upload_to='uploads'),
        ),
    ]
