# Generated by Django 4.2.7 on 2023-11-04 10:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_userdetails_uploaded_at_userdetails_disease_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='uploaded_date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='hospital_name',
            field=models.CharField(default='no Hospital name', max_length=100),
        ),
    ]
