# Generated by Django 4.2.7 on 2023-11-05 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_userdetails_date_userdetails_uploaded_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='medicines_prescribed',
            field=models.TextField(default='No Medicines Prescribed'),
        ),
    ]
